CREATE TABLE Users(
 Id INT PRIMARY KEY IDENTITY NOT NULL,
 FirstName NVARCHAR(50) NOT NULL,
 LastName NVARCHAR(50) NOT NULL,
 Email NVARCHAR(80) UNIQUE NOT NULL ,
 PasswordHash VARCHAR(250) NOT NULL,
 PhonNumber VARCHAR(20),
 AvatarUrl VARCHAR(200),
 Roles INT NOT NULL,
 CreatedAt DATE,
 IsActive BIT
 );

 CREATE TABLE RefreshToken(
 Id INT NOT NULL PRIMARY KEY IDENTITY,
 UserId INT NOT NULL,
 IsRevoked BIT NOT NULL,
 Value VARCHAR(100),
 ExpiryDate DATE

 FOREIGN KEY(UserId) REFERENCES  Users(Id)
);
